name: Scott Russell
author: Scott Russell
markdown: redcarpet
pygments: true
baseurl: /
url: 
description: Developer & Entrepreneur
github: http://www.github.com/srussell123
twitter: http://www.twitter.com/Sukotto123
linkedin: www.linkedin.com/in/scottbrussell/
email: scottbrussell@gmail.com
location:
disqus: scottbrussell

##Make sure to edit the above fields, especially for disqus. 

